version: '3'

services:
  concourse-db:
    image: postgres
    volumes: ["database:/database"]
    environment:
    - POSTGRES_USER=concourse
    - PGDATA=/database

  concourse:
    image: concourse/concourse
    command: quickstart
    privileged: true
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    environment:
    - CONCOURSE_POSTGRES_HOST=concourse-db
    - CONCOURSE_POSTGRES_USER=concourse
    - CONCOURSE_POSTGRES_PASSWORD=concourse
    - CONCOURSE_POSTGRES_DATABASE=concourse
    - CONCOURSE_EXTERNAL_URL=http://localhost:8080
    - CONCOURSE_ADD_LOCAL_USER=demo:demo
    - CONCOURSE_MAIN_TEAM_LOCAL_USER=demo

  nexus:
    image: sonatype/nexus3
    ports: ["8081:8081"]
    volumes: ["nexus-data:/nexus-data"]

  gitbucket:
    image: gitbucket/gitbucket
    ports: ["8000:8080"]
    volumes: ["gitbucket:/gitbucket"]

volumes:
  database:
  nexus-data:
  gitbucket:
